data:
  private:
    root: data/dichalcogenides_private
    defects: data/dichalcogenides_private/defects
    features: data/features.csv
model:
  megnet: "weights/val_mae_00750_0.010320.hdf5"
  boosting: "weights/boosting.cbm"
